#!/bin/sh

#kill other instances of mousejail if they exists
MOUSEJAIL_COUNT=$(pgrep -f '/bin/sh\s.*/bin/mousejail\s' | wc -w)
if [ "$MOUSEJAIL_COUNT" -gt 0 ]; then
    echo "Mousejail already running. Kill all processes and exit."
    killall mousejail 
    exit 1
fi

